name: Harbor Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Add a debug step to check if secrets are correctly being used
      - name: Print HARBOR_USERNAME (debug only, remove after verification)
        run: echo "${{ vars.HARBOR_USERNAME }}"
        # Add a debug step to check if secrets are correctly being used
      - name: Print HARBOR_PW (debug only, remove after verification)
        run: echo "${{ secrets.HARBOR_PASSWORD }}"

  


      # - name: Build Docker Image
      #   run: docker build -t synapse:dev ./Deploy

      # - name: Log in to Harbor
      #   run: echo "$HARBOR_PASSWORD" | docker login https://registry.eu.aperturect.com --username "$HARBOR_USERNAME" --password-stdin

      # - name: Tag Docker Image for Harbor
      #   run: docker tag synapse:dev https://registry.eu.aperturect.com/library/synapse:dev

      # - name: Push Docker Image to Harbor
      #   run: docker push https://registry.eu.aperturect.com/library/synapse:dev
