name: Harbor Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t synapse:dev --platform linux/amd64 ./Deploy

      - name: Log in to Harbor
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login https://registry.eu.aperturect.com --username "${{ vars.HARBOR_USERNAME }}" --password-stdin

      - name: Push Docker Image to Harbor
        run: docker push https://registry.eu.aperturect.com/library/synapse:dev
