name: Release Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t registry.eu.aperturect.com/library/synapse:${{ github.event.release.tag_name }} --platform linux/amd64 ./Deploy

      - name: Log in to Harbor
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login registry.eu.aperturect.com --username "${{ vars.HARBOR_USERNAME }}" --password-stdin

      - name: Push Docker Image to Harbor
        run: docker push registry.eu.aperturect.com/library/synapse:${{ github.event.release.tag_name }}

      - name: Tag Docker Image as latest for Harbor
        run: docker tag registry.eu.aperturect.com/library/synapse:${{ github.event.release.tag_name }} registry.eu.aperturect.com/library/synapse:latest

      - name: Push Docker Image (latest) to Harbor
        run: docker push registry.eu.aperturect.com/library/synapse:latest
